FROM golang:1.24 AS builder

WORKDIR /temp

COPY . .

RUN go build -o main .
# RUN go GOOS=linux build -o main .

FROM gcr.io/distroless/base

WORKDIR /app
COPY --from=builder /temp/main .

CMD ["./main"]
