services:
  godev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  goprod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
    environment:
      - ENV=production
