FROM golang:1.24 AS builder

WORKDIR /temp

COPY . .

# RUN go build -o server .
RUN GOOS=linux go build -ldflags="-w -s" -o server .

FROM gcr.io/distroless/base

WORKDIR /app
COPY --from=builder /temp/server .

CMD ["./server"]
